ProcessWorkOrders/Models/WorkOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProcessWorkOrders.Models
{
    public class WorkOrder
    {
        [Key]
        public int WorkOrderNumber { get; set; }
        public string InventoryItemNumber { get; set; }
        public string Description { get; set; }
        public string CustomerName { get; set; }
        public double Quantity { get; set; }
        public string ExtrusionInstruction { get; set; }
        public string? PrintingInstruction { get; set; }
        public string? PrintingUri { get; set; }
        public string? VentingUri { get; set; }
        public string LabelingInstruction {get; set;}
        public int WorkCenter { get; set; }
        public string? Notes { get; set; }
        public int SalesOrderNumber { get; set; }
        public DateTime DateNeeded { get; set; }
        public DateTime DateCreated { get; set; }
        public double RunSpeed { get; set; }
        public string Construction { get; set; }
        public bool IsFda { get; set; }

        public List<Roll> Rolls { get; set; } = new List<Roll>();
    }
}

ProcessWorkOrders/Controllers/RollsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProcessWorkOrders.Context;
using ProcessWorkOrders.Models;

namespace ProcessWorkOrders.Controllers
{
    public class RollsController : Controller
    {
        private readonly WorkOrderDbContext _context;

        public RollsController(WorkOrderDbContext context)
        {
            _context = context;
        }

        // GET: Rolls?workOrderNumber=5
        public IActionResult Index(int? workOrderNumber)
        {
            if(workOrderNumber!=null)
            {
            var rolls = _context.WorkOrders.Include(_ => _.Rolls).SingleOrDefault(_ => _.WorkOrderNumber == workOrderNumber);
            return View(rolls.Rolls);
            }
            else
            {
                return View(new List<Roll>());
            }
        }

        // GET: Rolls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roll = await _context.Rolls
                .FirstOrDefaultAsync(m => m.Number == id);
            if (roll == null)
            {
                return NotFound();
            }

            return View(roll);
        }

        // GET: Rolls/Create
        public IActionResult Create()
        {
            ViewData["WorkOrder"] = 2;
            return View();
        }

        // POST: Rolls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Weight,Number,Width,Length,QuantityPer,Gauge,Operator,WorkOrderWorkOrderNumber")] Roll roll)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roll);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(roll);
        }

        // GET: Rolls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roll = await _context.Rolls.FindAsync(id);
            if (roll == null)
            {
                return NotFound();
            }
            return View(roll);
        }

        // POST: Rolls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Number,Width,Length,QuantityPer,Gauge,Operator")] Roll roll)
        {
            if (id != roll.Number)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roll);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RollExists(roll.Number))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roll);
        }

        // GET: Rolls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roll = await _context.Rolls
                .FirstOrDefaultAsync(m => m.Number == id);
            if (roll == null)
            {
                return NotFound();
            }

            return View(roll);
        }

        // POST: Rolls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roll = await _context.Rolls.FindAsync(id);
            _context.Rolls.Remove(roll);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RollExists(int id)
        {
            return _context.Rolls.Any(e => e.Number == id);
        }
    }
}

ProcessWorkOrders/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProcessWorkOrders.Context;
using ProcessWorkOrders.Models;

namespace ProcessWorkOrders.Controllers
{
    public class WorkOrderController : Controller
    {
        private readonly WorkOrderDbContext _context;
        public WorkOrderController(WorkOrderDbContext context)
        {
            _context = context;
        }
        // GET: WorkOrderController
        public ActionResult Index()
        {
            var workOrders = _context.WorkOrders.ToList();
            return View(workOrders);
        }

        // GET: WorkOrderController/Details/5
        public ActionResult Details(int id)
        {
            var order = _context.WorkOrders.Include(_=>_.Rolls).Where(_ => _.WorkOrderNumber == id).SingleOrDefault();
            if (order==null)
            {
                
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: WorkOrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkOrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WorkOrder workOrder)
        {
            if (workOrder != null)
            {
                try
                {
                    _context.Add(workOrder);
                    _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            else return View();
        }

        // GET: WorkOrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: WorkOrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WorkOrderController/Delete/5
        public ActionResult Delete(int id)
        {
            var workOrder = _context.WorkOrders.SingleOrDefault(_ => _.WorkOrderNumber == id);
            _context.Remove(workOrder);
            _context.SaveChangesAsync();
            return View();
        }

        // POST: WorkOrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProcessWorkOrders/Views/WorkOrder/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model WorkOrder
<div class="text-center">
    <h1>Work order</h1>
    <h3>Create/Edit</h3>
</div>

<form class="form-group" asp-action="Create" method="post">
    <label class="col-form-label" for="InventoryItemNumber">Item Number</label>
    <input name="InventoryItemNumber" asp-for="@Model.InventoryItemNumber" type="text" class="form-control" />
    <label class="col-form-label" for="Description">Item Description</label>
    <input name="Description" asp-for="@Model.Description" type="text" class="form-control" />
    <label class="col-form-label" for="CustomerName">Customer Name</label>
    <input name="CustomerName" asp-for="@Model.CustomerName" type="text" class="form-control" />
    <label class="col-form-label" for="SalesOrderNumber">Sales Order Number</label>
    <input name="SalesOrderNumber" asp-for="@Model.SalesOrderNumber" type="number" class="form-control" />
    <label class="col-form-label" for="Quantity">Quantity</label>
    <input name="Quantity" asp-for="@Model.Quantity" type="number" class="form-control" />
    <label class="col-form-label" for="ExtrusionInstruction">Extrusion Instructions</label>
    <input name="ExtrusionInstruction" asp-for="@Model.ExtrusionInstruction" type="text" class="form-control" />
    <label class="col-form-label" for="PrintingInstruction">Printing Instructions</label>
    <input name="PrintingInstruction" asp-for="@Model.PrintingInstruction" type="text" class="form-control" />
    <label class="col-form-label" for="PrintingUri">Printing Link</label>
    <input name="PrintingUri" asp-for="@Model.PrintingUri" type="url" class="form-control" />
    <label class="col-form-label" for="VentingUri">Venting Link</label>
    <input name="VentingUri" asp-for="@Model.VentingUri" type="url" class="form-control" />
    <label class="col-form-label" for="LabelingInstruction">Labeling Instructions</label>
    <input name="LabelingInstruction" asp-for="@Model.LabelingInstruction" type="text" class="form-control" />
    <label class="col-form-label" for="WorkCenter">Work Center</label>
    <input name="WorkCenter" asp-for="@Model.WorkCenter" type="number" class="form-control" />
    <label class="col-form-label" for="Notes">Notes</label>
    <input name="Notes" asp-for="@Model.Notes" type="text" class="form-control" />
    <label class="col-form-label" for="DateNeeded">Date Needed</label>
    <input name="DateNeeded" asp-for="@Model.DateNeeded" type="date" class="form-control" />
    <label class="col-form-label" for="DateCreated">Created Date</label>
    <input name="DateCreated" asp-for="@Model.DateCreated" type="date" class="form-control" />
    <label class="col-form-label" for="RunSpeed">Run Speed</label>
    <input name="RunSpeed" asp-for="@Model.RunSpeed" type="number" class="form-control" />
    <label class="col-form-label" for="Construction">Construction (tubing/cf/js/sws/dws/gt/mfold)</label>
    <input name="Construction" asp-for="@Model.Construction" type="text" class="form-control" />
    <label class="form-check-label" for="IsFda">FDA?</label>
    <input name="IsFda" asp-for="@Model.IsFda" type="checkbox" class="form-check" />
    <button type="reset" class="btn btn-info">Reset</button>
    <button type="submit" class="btn btn-success">Submit</button>
</form>

ProcessWorkOrders/Views/WorkOrder/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@functions{
    public string background(string construction)
    {
        if (construction == "Tubing" || construction.ToUpper() == "JS")
        {
            return "DodgerBlue";
        }
        else if (construction == "POR")
        {
            return "Green";
        }
        else if (construction == "Stock Tubing")
        {
            return "Yellow";
        }
        else return "white";
    }
}
@model WorkOrder 
<body style="background-color:@background(Model.Construction)">
<div class="text-center font-weight-bolder text-lg-center">
    Work Order: @Model.WorkOrderNumber
    <span class="btn-group-sm">
        <button class="btn btn-sm btn-success">Select</button>
        <button class="btn btn-sm btn-danger">Skip</button>
        <button class="btn btn-sm btn-info">Edit</button>
    </span>
</div>
<div class="border-bottom">
    <p>
        <b>Customer:</b> @Model.CustomerName
    </p>
    <p><b>Description:</b> @Model.Description</p>
    <p>
        <b>Item Number:</b> @Model.InventoryItemNumber
    </p>
    <p>
        <b>Sales Order:</b> @Model.SalesOrderNumber
    </p>
    <p><b>Date Needed:</b>@Model.DateNeeded</p>
    <p><b>Date Created:</b>@Model.DateCreated</p>
</div>
<br />
<div class="text-center">
<span class="text-center">Run Speed:<em> @Model.RunSpeed</em>  Work Center:<em> @Model.WorkCenter</em> Quantity:<em> @Model.Quantity</em>  </span>
</div>
<div>
    <p class="font-weight-bold">
    Extrustion Instructions
    </p>
    <p>
    @Model.ExtrusionInstruction
    </p>
</div>
<div>
    <p class="font-weight-bold">
    Printing Instructions
    </p>
    <p>
    @Model.PrintingInstruction
    <a href="@Model.PrintingUri">Print File</a>
    </p>
    <br />
</div>
<div>
    <p class="font-weight-bold">
    Venting Instructions
    </p>
    <p>
    <a href="@Model.VentingUri">Vent File</a>
    </p>
    <br />
</div>
<div>
    <p class="font-weight-bold">Labeling Instructions</p>
    <p>@Model.LabelingInstruction</p>
</div>
<div>
    <p class="font-weight-bold">Notes:</p>
    <p>@Model.Notes</p>
</div>
<div class="text-center">
    <h3>Rolls</h3>
</div>
<table class="table table-bordered table-striped">
    <thead class="table-dark">
        <tr>
            <td>Roll #</td>
            <td>Weight</td>
            <td>Width As Sheet</td>
            <td>Length</td>
            <td>Number On Roll</td>
            <td>Gauge</td>
            <td>Viscosity</td>
            <td>Operator</td>
        </tr>
    </thead>
    <tbody>
        @foreach(Roll r in Model.Rolls)
        {

        <tr>
            <td>@r.Id</td>
            <td>@r.Weight</td>
            <td>@r.Width</td>
            <td>@r.Length</td>
            <td>@r.QuantityPer</td>
            <td>@r.Gauge</td>
            <td>-</td>
            <td>@r.Operator</td>

        </tr>
        }
        <tr>
            @Html.ActionLink("New", "Create", "Rolls")
        </tr>
    </tbody>
</table>
</body>

ProcessWorkOrders/Views/WorkOrder/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@Html.ActionLink("Create", "Create", "WorkOrder")

<div class="text-center">
    <h1>Search</h1>
    <form asp-action="Details">
        <label for="id">Work Order Number</label>
        <input name="id" id="id" for="id" type="number" />
        <button type="submit">Get Work Order</button>
    </form>

</div>